# Generated by Django 5.0.6 on 2024-06-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='billdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now=True)),
                ('Customer', models.CharField(blank=True, max_length=100, null=True)),
                ('Total', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='customerdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.CharField(blank=True, max_length=100, null=True)),
                ('Place', models.CharField(blank=True, max_length=1000, null=True)),
                ('Mobile', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='invoicedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now=True)),
                ('Total', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='milkdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now=True)),
                ('Farmer', models.CharField(blank=True, max_length=1000, null=True)),
                ('Milk', models.FloatField(blank=True, null=True)),
                ('FAT', models.FloatField(blank=True, null=True)),
                ('SNF', models.FloatField(blank=True, null=True)),
                ('Rate', models.FloatField(blank=True, null=True)),
                ('Totalrate', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pricechart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fat', models.FloatField(blank=True, null=True)),
                ('snf', models.FloatField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='productdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, max_length=1000, null=True)),
                ('Price', models.FloatField(blank=True, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Product')),
            ],
        ),
        migrations.CreateModel(
            name='salesdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now=True)),
                ('Product', models.CharField(blank=True, max_length=100, null=True)),
                ('Price', models.FloatField(blank=True, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Total', models.FloatField(blank=True, null=True)),
                ('Customer', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
