# Generated by Django 5.0.6 on 2024-06-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attendancedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now=True)),
                ('Empname', models.CharField(blank=True, max_length=100, null=True)),
                ('Attendance', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='employeedb',
            fields=[
                ('Empname', models.CharField(blank=True, max_length=100, null=True)),
                ('Designation', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.CharField(blank=True, max_length=1000, null=True)),
                ('Dateofbirth', models.CharField(blank=True, max_length=1000, null=True)),
                ('Gender', models.CharField(blank=True, max_length=10, null=True)),
                ('Mobile', models.IntegerField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Salary', models.IntegerField(blank=True, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='employee')),
            ],
        ),
        migrations.CreateModel(
            name='farmerdb',
            fields=[
                ('Cardno', models.CharField(blank=True, max_length=100, null=True)),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.CharField(blank=True, max_length=1000, null=True)),
                ('Dateofbirth', models.CharField(blank=True, max_length=1000, null=True)),
                ('Gender', models.CharField(blank=True, max_length=10, null=True)),
                ('Mobile', models.IntegerField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='employee')),
            ],
        ),
        migrations.CreateModel(
            name='imagedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='postdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
